In [56]:
import pandas as pd

In [57]:
input_file_path = "asu.tsv"  # Replace with the path to your input file
output_file_path = "RACS.csv"  # Replace with the path to your output file

with open(input_file_path, "r") as input_file:
    with open(output_file_path, "w") as output_file:
        lines_to_delete = 108
        lines_to_skip = [110,111]
        for i, line in enumerate(input_file, 1):
            if i > lines_to_delete:
                if i not in lines_to_skip:
                    output_file.write(line)

In [96]:
df = pd.read_csv('RACS.csv',sep='\t')

/var/folders/1s/06d7kngs1t783rb69n44z54c0000gn/T/ipykernel_74718/707847321.py:1: DtypeWarning: Columns (24,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('RACS.csv',sep='\t')

In [91]:
df.head()

,_RAJ2000,_DEJ2000,RACS-DR1,ID,Tile,SBID,MJD,Ng,RAJ2000,DEJ2000,...,bmin0,e_bmin0,PA0,e_PA0,Mult,Sep,Noise,GLON,GLAT,Flag
0,00 12 37.84513,+10 18 08.8240,J001237.8+101808,RACS_0000+12A_1071,RACS_0000+12A,8578,58599.06929,1,3.157688,10.302451,...,,2.27,0.00,17.11,S,3.8431,0.329,107.518268,-51.404165,-
1,00 12 37.25447,+10 19 38.9530,J001237.2+101938,RACS_0000+12A_1072,RACS_0000+12A,8578,58599.06929,1,3.155227,10.327487,...,,0.53,0.00,29.91,S,3.8262,0.324,107.524147,-51.379281,-
2,00 12 36.90027,+11 02 37.8740,J001236.9+110237,RACS_0000+12A_1079,RACS_0000+12A,8578,58599.06929,1,3.153751,11.043854,...,26.12,5.76,33.30,20.82,S,3.4484,0.367,107.793667,-50.683253,-
3,00 12 34.30200,+11 06 28.2420,J001234.3+110628,RACS_0000+12A_1084,RACS_0000+12A,8578,58599.06929,1,3.142925,11.107845,...,,2.5,0.00,51.49,S,3.4105,0.379,107.801283,-50.618566,-
4,00 12 31.15773,+10 39 07.2610,J001231.1+103907,RACS_0000+12A_1088,RACS_0000+12A,8578,58599.06929,1,3.129824,10.652017,...,5.13,3.92,0.26,35.41,S,3.6220,0.319,107.609691,-51.058232,-

In [109]:
df.tail()

,_RAJ2000,_DEJ2000,RACS-DR1,ID,Tile,SBID,MJD,Ng,RAJ2000,DEJ2000,...,bmin0,e_bmin0,PA0,e_PA0,Mult,Sep,Noise,GLON,GLAT,Flag
1495755,23 43 22.17167,-41 29 03.9260,J234322.1-412903,RACS_2359-43A_5447,RACS_2359-43A,8600,58604.06235,1,355.842382,-41.484424,...,,1.81,0.00,32.06,S,3.8780,0.487,342.757113,-69.981532,-
1495756,23 43 20.31047,-41 15 53.2330,J234320.3-411553,RACS_2359-43A_5460,RACS_2359-43A,8600,58604.06235,1,355.834627,-41.264787,...,9.21,3.26,162.45,35.51,S,4.0254,0.515,343.259652,-70.118917,-
1495757,23 43 19.61067,-41 10 26.6300,J234319.6-411026,RACS_2359-43A_5464,RACS_2359-43A,8600,58604.06235,1,355.831711,-41.174064,...,3.85,0.41,2.02,50.21,S,4.0880,0.544,343.468787,-70.175407,-
1495758,23 43 23.95347,-40 57 35.3880,J234323.9-405735,RACS_2359-43A_5465,RACS_2359-43A,8600,58604.06235,1,355.849806,-40.959830,...,,3.05,0.00,32.24,S,4.2265,0.627,343.931738,-70.322400,-
1495759,23 57 47.56293,-41 49 57.3130,J235747.5-414957,RACS_2359-43A_6595,RACS_2359-43A,8600,58604.06235,1,359.448179,-41.832587,...,34.61,6.21,49.86,16.57,S,2.0797,0.475,336.231268,-71.652558,-

In [97]:
df.shape

(2123638, 35)

In [93]:
df.columns

Index(['_RAJ2000', '_DEJ2000', 'RACS-DR1', 'ID', 'Tile', 'SBID', 'MJD', 'Ng',
       'RAJ2000', 'DEJ2000', 'e_RAJ2000', 'e_DEJ2000', 'Ftot', 'e_Ftot',
       's_Ftot', 'Fpk', 'e_Fpk', 'amaj', 'e_amaj', 'bmin', 'e_bmin', 'PA',
       'e_PA', 'amaj0', 'e_amaj0', 'bmin0', 'e_bmin0', 'PA0', 'e_PA0', 'Mult',
       'Sep', 'Noise', 'GLON', 'GLAT', 'Flag'],
      dtype='object')

In [98]:
df.describe()

,SBID,MJD,Ng,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,Ftot,e_Ftot,s_Ftot,...,bmin,e_bmin,PA,e_PA,PA0,e_PA0,Sep,Noise,GLON,GLAT
count,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,...,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06,2.123638e+06
mean,1.051419e+04,5.874996e+04,1.159658e+00,1.793148e+02,-1.966705e+01,1.185448e+00,1.218138e+00,2.264695e+01,8.072564e-01,2.351007e+00,...,2.536356e+01,2.138964e+00,9.277611e+01,3.243694e+01,6.462759e+01,3.243694e+01,2.342269e+00,3.520355e-01,2.056599e+02,-8.764283e+00
std,2.312895e+03,1.739923e+02,5.510795e-01,1.048179e+02,2.913631e+01,9.317074e-01,9.623981e-01,3.593106e+02,2.892517e+00,2.530711e+01,...,3.169963e+00,1.488691e+00,5.446591e+01,3.106886e+01,6.185212e+01,3.106886e+01,8.772139e-01,2.859953e-01,1.121664e+02,4.038254e+01
min,8.540000e+03,5.859458e+04,1.000000e+00,2.400000e-05,-8.468075e+01,0.000000e+00,0.000000e+00,6.000000e-03,2.000000e-03,5.000000e-01,...,7.690000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e-03,2.000000e-03,7.200000e-05,-8.998117e+01
25%,8.586000e+03,5.860107e+04,1.000000e+00,8.611280e+01,-4.194239e+01,4.300000e-01,4.300000e-01,2.916000e+00,5.280000e-01,9.380000e-01,...,2.400000e+01,8.400000e-01,4.320000e+01,1.297000e+01,0.000000e+00,1.297000e+01,1.710100e+00,2.620000e-01,9.568931e+01,-4.057873e+01
50%,8.676000e+03,5.860982e+04,1.000000e+00,1.797900e+02,-1.858961e+01,1.030000e+00,1.050000e+00,5.316000e+00,6.640000e-01,1.176000e+00,...,2.518000e+01,1.950000e+00,9.430000e+01,2.425000e+01,4.918000e+01,2.425000e+01,2.453400e+00,3.120000e-01,2.371643e+02,-1.511707e+01
75%,1.252200e+04,5.893617e+04,1.000000e+00,2.692831e+02,4.740495e+00,1.740000e+00,1.790000e+00,1.312600e+01,8.870000e-01,1.759000e+00,...,2.633000e+01,3.260000e+00,1.424800e+02,4.078000e+01,1.241400e+02,4.078000e+01,3.018200e+00,3.820000e-01,2.973513e+02,2.375214e+01
max,1.499800e+04,5.902185e+04,6.400000e+01,3.599998e+02,2.912713e+01,2.487000e+01,4.665000e+01,4.019498e+05,3.393022e+03,2.815987e+04,...,2.847600e+02,2.574000e+01,1.800000e+02,1.800000e+02,1.800000e+02,1.800000e+02,5.237900e+00,1.794190e+02,3.599999e+02,8.992650e+01

In [99]:
df = df[~df['_DEJ2000'].str.contains('\+')]
df.shape

(1495760, 35)

In [102]:
df.reset_index(inplace = True,drop=True)

In [103]:
df.to_csv('RACS_filtered.csv')

In [106]:
df.tail()

,_RAJ2000,_DEJ2000,RACS-DR1,ID,Tile,SBID,MJD,Ng,RAJ2000,DEJ2000,...,bmin0,e_bmin0,PA0,e_PA0,Mult,Sep,Noise,GLON,GLAT,Flag
1495755,23 43 22.17167,-41 29 03.9260,J234322.1-412903,RACS_2359-43A_5447,RACS_2359-43A,8600,58604.06235,1,355.842382,-41.484424,...,,1.81,0.00,32.06,S,3.8780,0.487,342.757113,-69.981532,-
1495756,23 43 20.31047,-41 15 53.2330,J234320.3-411553,RACS_2359-43A_5460,RACS_2359-43A,8600,58604.06235,1,355.834627,-41.264787,...,9.21,3.26,162.45,35.51,S,4.0254,0.515,343.259652,-70.118917,-
1495757,23 43 19.61067,-41 10 26.6300,J234319.6-411026,RACS_2359-43A_5464,RACS_2359-43A,8600,58604.06235,1,355.831711,-41.174064,...,3.85,0.41,2.02,50.21,S,4.0880,0.544,343.468787,-70.175407,-
1495758,23 43 23.95347,-40 57 35.3880,J234323.9-405735,RACS_2359-43A_5465,RACS_2359-43A,8600,58604.06235,1,355.849806,-40.959830,...,,3.05,0.00,32.24,S,4.2265,0.627,343.931738,-70.322400,-
1495759,23 57 47.56293,-41 49 57.3130,J235747.5-414957,RACS_2359-43A_6595,RACS_2359-43A,8600,58604.06235,1,359.448179,-41.832587,...,34.61,6.21,49.86,16.57,S,2.0797,0.475,336.231268,-71.652558,-